const classrooms = {
    2: [{ name: 'KMC251', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 16 }],
    5: [
      { name: 'KMD557', typeFi: 'Digitila', typeEn: 'Digital Room', capacity: 39 },
      { name: 'KMC592', typeFi: 'Digitila', typeEn: 'Digital Room', capacity: 40 },
      { name: 'KMC565', typeFi: 'Digitila', typeEn: 'Digital Room', capacity: 43 },
      { name: 'KMC523.2', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD503.3', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMC523.3', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 2 },
      { name: 'KMD558', typeFi: 'Medialaboratorio', typeEn: 'Media Lab', capacity: 38 },
      { name: 'KMD569', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 30 },
      { name: 'KME551', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 39 },
      { name: 'KME559', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME562', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME561', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 41 },
      { name: 'KMC557', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 62 },
      { name: 'KMD550', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 80 },
      { name: 'KMD503.1', typeFi: 'Taltiointitila', typeEn: 'Recording Room', capacity: 4 },
      { name: 'KME572', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 6 },
      { name: 'KMC551', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 10 },
      { name: 'KME590', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 10 },
    ],
    6: [
      { name: 'KMD653', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD654', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KME673', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD659', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 30 },
      { name: 'KMD652', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KMD657', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME661', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME659', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 78 },
      { name: 'KMD650', typeFi: 'Ryhmätyötila', typeEn: 'Group Workspace', capacity: 5 },
      { name: 'KMD651', typeFi: 'Ryhmätyötila', typeEn: 'Group Workspace', capacity: 5 },
      { name: 'KME662', typeFi: 'Smart IoT -laboratorio', typeEn: 'Smart IoT Laboratory', capacity: 32 },
      { name: 'KMD658', typeFi: 'Smart IoT -laboratorio', typeEn: 'Smart IoT Laboratory', capacity: 43 },
      { name: 'KME654', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME655', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME656', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME651', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 6 },
      { name: 'KME690', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 18 },
    ],
    7: [
      { name: 'KMD753', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD755', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD756', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 1 },
      { name: 'KMD754', typeFi: 'Henkilöstön työtila', typeEn: 'Staff Workspace', capacity: 2 },
      { name: 'KMD750', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 32 },
      { name: 'KMD758', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 35 },
      { name: 'KMD759', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 35 },
      { name: 'KME759', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 36 },
      { name: 'KMD751', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KMD757', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME751', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 40 },
      { name: 'KME762', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 45 },
      { name: 'KME761', typeFi: 'Oppimistila', typeEn: 'Learning Space', capacity: 46 },
      { name: 'KME752', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME753', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME754', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME755', typeFi: 'Työtila', typeEn: 'Workspace', capacity: 1 },
      { name: 'KME770', typeFi: 'VR/AR -laboratorio', typeEn: 'VR/AR Laboratory', capacity: 16 },
      { name: 'KME772', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 6 },
      { name: 'KME773', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 6 },
      { name: 'KME790', typeFi: 'Yhteistyötila', typeEn: 'Collaboration Room', capacity: 12 },
    ],
    
  };

  export default classrooms;
