[
	{
		"roomNumber": "KMC251",
		"floor": "2",
		"building": "KM",
		"wing": "C",
		"persons": "16",
		"squareMeters": "32.5",
		"details": "Yhteistyötila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC501",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "20",
		"squareMeters": "124.5",
		"details": "Hissiaula",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC523.2",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "1",
		"squareMeters": "6.5",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC523.3",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "2",
		"squareMeters": "8",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC523.4",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "4",
		"squareMeters": "7.5",
		"details": "Avoin oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KMC551",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "10",
		"squareMeters": "22",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC557",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "62",
		"squareMeters": "120.5",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC565",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "43",
		"squareMeters": "125.5",
		"details": "Digitila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC586",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "1",
		"squareMeters": "8",
		"details": "Tarkkaamo",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMC590",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "4",
		"squareMeters": "51",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KMC591",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "4",
		"squareMeters": "28",
		"details": "METKA",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KMC592",
		"floor": "5",
		"building": "KM",
		"wing": "C",
		"persons": "40",
		"squareMeters": "100",
		"details": "Digitila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD503.1",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "4",
		"squareMeters": "16",
		"details": "Taltiointitila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD503.3",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "6.5",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD503.4",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "6",
		"details": "Tarkkaamo",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD550",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "80",
		"squareMeters": "126",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD557",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "39",
		"squareMeters": "97.5",
		"details": "Digitila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD558",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "38",
		"squareMeters": "74.5",
		"details": "Medialaboratorio",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD569",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "35",
		"squareMeters": "63",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD590",
		"floor": "5",
		"building": "KM",
		"wing": "D",
		"persons": "2",
		"squareMeters": "38.5",
		"details": "Varasto/medialaboratorio",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KMD616",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "10",
		"squareMeters": "0",
		"details": "Hissiaula",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD650",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "5",
		"squareMeters": "10.5",
		"details": "Ryhmätyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD651",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "5",
		"squareMeters": "11",
		"details": "Ryhmätyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD652",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "40",
		"squareMeters": "98",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD653",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "6.5",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD654",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "5",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD657",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "40",
		"squareMeters": "86",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD658",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "43",
		"squareMeters": "112",
		"details": "Smart IoT -laboratorio",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD659",
		"floor": "6",
		"building": "KM",
		"wing": "D",
		"persons": "43",
		"squareMeters": "112",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD716",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "10",
		"squareMeters": "0",
		"details": "Hissiaula",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD750",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "32",
		"squareMeters": "60",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KMD751",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "40",
		"squareMeters": "76",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD753",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "7",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD754",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "2",
		"squareMeters": "8",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD755",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "6",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD756",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "1",
		"squareMeters": "6",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD757",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "40",
		"squareMeters": "86.5",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD758",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "35",
		"squareMeters": "73",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KMD759",
		"floor": "7",
		"building": "KM",
		"wing": "D",
		"persons": "35",
		"squareMeters": "63.5",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME551",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "39",
		"squareMeters": "79",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME559",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "40",
		"squareMeters": "96",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KME561",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "41",
		"squareMeters": "107",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME562",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "40",
		"squareMeters": "90.5",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME570",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "30",
		"squareMeters": "66.5",
		"details": "Opiskelijoiden tila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KME572",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "6",
		"squareMeters": "16.5",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME590",
		"floor": "5",
		"building": "KM",
		"wing": "E",
		"persons": "10",
		"squareMeters": "35",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME651",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "6",
		"squareMeters": "16",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME652",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "5",
		"squareMeters": "16",
		"details": "Hiljainen tila",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KME654",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME655",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME656",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME659",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "78",
		"squareMeters": "126",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME661",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "40",
		"squareMeters": "95.5",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME662",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "32",
		"squareMeters": "88.5",
		"details": "Smart IoT -laboratorio",
		"reservableStudents": "false",
		"reservableStaff": "false"
	},
	{
		"roomNumber": "KME670",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "36",
		"squareMeters": "83",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME673",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "11",
		"details": "Henkilöstön työtila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME690",
		"floor": "6",
		"building": "KM",
		"wing": "E",
		"persons": "18",
		"squareMeters": "0",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME751",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "40",
		"squareMeters": "0",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME752",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME753",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME754",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME755",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "1",
		"squareMeters": "6",
		"details": "Työtila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME759",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "36",
		"squareMeters": "77",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME761",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "46",
		"squareMeters": "96",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME762",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "45",
		"squareMeters": "88",
		"details": "Oppimistila",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME770",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "16",
		"squareMeters": "61",
		"details": "VR/AR -laboratorio",
		"reservableStudents": "false",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME772",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "6",
		"squareMeters": "16",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME773",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "6",
		"squareMeters": "16.5",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	},
	{
		"roomNumber": "KME790",
		"floor": "7",
		"building": "KM",
		"wing": "E",
		"persons": "12",
		"squareMeters": "35",
		"details": "Yhteistyötila",
		"reservableStudents": "true",
		"reservableStaff": "true"
	}
]